events {
    worker_connections 1024;
}

http {

    # Upstream com servidores da aplicação (load balancing)
    upstream backend_servers {
        least_conn;

        server 172.31.0.37:80;
        server 172.31.0.151:80;
        server 172.31.0.149:80;
    }

    server {
        listen 4500;
        server_name localhost;

        location / {
            proxy_pass http://backend_servers;

            # Headers importantes para proxy
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Timeout de conexão
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }
    }

}
